version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - TZ=UTC
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TURBOPACK_WATCH_POLLING=1
      - TURBOPACK_WATCH_IGNORE_PATTERN=node_modules
      - NEXT_PUBLIC_API_URL=http://api:8080
    networks:
      - projectpulse-network
    restart: unless-stopped
    depends_on:
      - api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      - TZ=UTC
      - GO_ENV=development
    depends_on:
      - postgres
      - redis
    networks:
      - projectpulse-network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: projectpulse
      POSTGRES_PASSWORD: projectpulse
      POSTGRES_DB: projectpulse
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - projectpulse-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U projectpulse" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - projectpulse-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  projectpulse-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
