services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production # Use the production stage
    volumes:
      - ./api/config:/app/config # Only mount config directory
    environment:
      - GO_ENV=production
    restart: always

  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - db_password

  redis:
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - redis_password

secrets:
  db_password:
    file: ./secrets/db_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
